### ISSUE TITLE
Bot suspended in splitting process.

### ISSUE THREAD

**Issue by LeoBonharts** [5MysterySD/Tele-LeechX#18]
Bot will be suspended when leech files bigger than 20gb it will ban in splitting process.

**Comment by 5MysterySD** [comment]
> Bot will be suspended when leech files bigger than 20gb it will ban in splitting process.

**Heroku Issue, Don't Use >16 GB For Split**

**Comment by LeoBonharts** [comment]
There is so many leech groups that work even when leech 30gb file it splits and upload files no suspend at all and all bots are on heroku, maybe splitting process is issue or maybe docker image.
