### ISSUE TITLE
add qbıttorent :)

### ISSUE THREAD

**Issue by mirrorclone** [5MysterySD/Tele-LeechX#3]
qbittorent fast aria torrent not good....

**Comment by 5MysterySD** [comment]
#### Will Try , Hope it will Work !!

**Comment by kamileecher** [comment]
İts work bro add qbittoreent tortoolkit

10 Eyl 2021 Cum 21:33 tarihinde MysterySD ***@***.***> şunu
yazdı:

**Comment by mirrorclone** [comment]
İ send message telegram
