### ISSUE TITLE
usinf docker and wsl2 no heroku using localhost 

### ISSUE THREAD

**Issue by satyamisme** [5MysterySD/Tele-LeechX#4]
2022-09-17 19:20:36 (3.32 MB/s) - ‘/app/tobrot/aria2/dht6.dat’ saved [8064/8064]

17-Sep-22 07:20:37 PM - tobrot - WARNING - [NOT FOUND] rclone.conf not found in Root Directory . [__init__.py:294]
17-Sep-22 07:20:37 PM - tobrot - INFO - [DB] DATABASE_URL not Provided [db_func.py:20]
2022-09-17 19:20:37,812 INFO [imdbpy.parser.http.piculet] /usr/local/lib/python3.10/dist-packages/imdb/parser/http/piculet.py:262: using lxml
17-Sep-22 07:20:37 PM - imdbpy.parser.http.piculet - INFO - using lxml [piculet.py:262]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer
    return await self.storage.get_peer_by_id(peer_id)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 148, in get_peer_by_id
    raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: Restarted & Updated Successfully!'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 69, in resolve_peer
    int(peer_id)
ValueError: invalid literal for int() with base 10: 'restarted&updatedsuccessfully!'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 72, in resolve_peer
    return await self.storage.get_peer_by_username(peer_id)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 160, in get_peer_by_username
    raise KeyError(f"Username not found: {username}")
KeyError: 'Username not found: restarted&updatedsuccessfully!'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/tobrot/__main__.py", line 218, in <module>
    a.edit_message_text("Restarted & Updated Successfully!", chat_id, msg_id)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text
    peer=await self.resolve_peer(chat_id),
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 74, in resolve_peer
    await self.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 361, in invoke
    return await self.send(query, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 331, in send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.UsernameInvalid: Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")

**Comment by satyamisme** [comment]
> 2022-09-17 19:20:36 (3.32 MB/s) - ‘/app/tobrot/aria2/dht6.dat’ saved [8064/8064]
> 
> 17-Sep-22 07:20:37 PM - tobrot - WARNING - [NOT FOUND] rclone.conf not found in Root Directory . [**init**.py:294] 17-Sep-22 07:20:37 PM - tobrot - INFO - [DB] DATABASE_URL not Provided [db_func.py:20] 2022-09-17 19:20:37,812 INFO [imdbpy.parser.http.piculet] /usr/local/lib/python3.10/dist-packages/imdb/parser/http/piculet.py:262: using lxml 17-Sep-22 07:20:37 PM - imdbpy.parser.http.piculet - INFO - using lxml [piculet.py:262] Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 60, in resolve_peer return await self.storage.get_peer_by_id(peer_id) File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 148, in get_peer_by_id raise KeyError(f"ID not found: {peer_id}") KeyError: 'ID not found: Restarted & Updated Successfully!'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 69, in resolve_peer int(peer_id) ValueError: invalid literal for int() with base 10: 'restarted&updatedsuccessfully!'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 72, in resolve_peer return await self.storage.get_peer_by_username(peer_id) File "/usr/local/lib/python3.10/dist-packages/pyrogram/storage/sqlite_storage.py", line 160, in get_peer_by_username raise KeyError(f"Username not found: {username}") KeyError: 'Username not found: restarted&updatedsuccessfully!'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/app/tobrot/**main**.py", line 218, in a.edit_message_text("Restarted & Updated Successfully!", chat_id, msg_id) File "/usr/local/lib/python3.10/dist-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap return loop.run_until_complete(coroutine) File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete return future.result() File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/messages/edit_message_text.py", line 82, in edit_message_text peer=await self.resolve_peer(chat_id), File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/resolve_peer.py", line 74, in resolve_peer await self.invoke( File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/advanced/invoke.py", line 77, in invoke r = await self.session.invoke( File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 361, in invoke return await self.send(query, timeout=timeout) File "/usr/local/lib/python3.10/dist-packages/pyrogram/session/session.py", line 331, in send RPCError.raise_it(result, type(data)) File "/usr/local/lib/python3.10/dist-packages/pyrogram/errors/rpc_error.py", line 91, in raise_it raise getattr( pyrogram.errors.exceptions.bad_request_400.UsernameInvalid: Telegram says: [400 USERNAME_INVALID] - The username is invalid (caused by "contacts.ResolveUsername")

*********************
The bot stops and wont start on restart command from telegram 


*************

**Comment by satyamisme** [comment]
17-Sep-22 07:40:51 PM **- tobrot - WARNING - Telegram says: [400 PEER_ID_INVALID] - The peer id being used is invalid or not** known yet. Make sure you meet the peer before interacting with it  [__main__.py:239]
17-Sep-22 07:40:52 PM - root - INFO -
________    ______           ______                 ______ ____  __
___  __/_______  /____       ___  / ___________________  /___  |/ /
__  /  _  _ \_  /_  _ \________  /  _  _ \  _ \  ___/_  __ \_    /
_  /   /  __/  / /  __//_____/  /___/  __/  __/ /__ _  / / /    |
/_/    \___//_/  \___/       /_____/\___/\___/\___/ /_/ /_//_/|_|
     [__main__.py:307]
17-Sep-22 07:40:52 PM - root - INFO - 🏠⬇️Leechlow  Has Started Running...🏃💨💨 [__main__.py:315]

**Comment by 5MysterySD** [comment]
> 

Problem has been Fixed on V2.9.1

Thank You ..
